### ISSUE TITLE
Exception handling

### ISSUE THREAD

**Issue by dgmltn** [dokar3/quickjs-kt#49]
Can you add a section to the README on how to properly handle js exceptions?

This does not work if an exception occurs in the js code. An error is thrown but this does not catch it:
```
                val result = try {
                    wrapper.evaluateJs(jscode)
                }
                catch (e: Exception) {
                    Logger.e { "Javascript error: $e" }
                    null
                }
```
throws this error:
```
Exception in thread "DefaultDispatcher-worker-10" java.lang.RuntimeException: Exception while trying to handle coroutine exception
	at kotlinx.coroutines.CoroutineExceptionHandlerKt.handlerException(CoroutineExceptionHandler.kt:33)
	at kotlinx.coroutines.internal.CoroutineExceptionHandlerImpl_commonKt.handleUncaughtCoroutineException(CoroutineExceptionHandlerImpl.common.kt:38)
	at kotlinx.coroutines.CoroutineExceptionHandlerKt.handleCoroutineException(CoroutineExceptionHandler.kt:28)
	at kotlinx.coroutines.StandaloneCoroutine.handleJobException(Builders.common.kt:190)
	at kotlinx.coroutines.JobSupport.finalizeFinishingState(JobSupport.kt:228)
	at kotlinx.coroutines.JobSupport.tryMakeCompletingSlowPath(JobSupport.kt:907)
	at kotlinx.coroutines.JobSupport.tryMakeCompleting(JobSupport.kt:864)
	at kotlinx.coroutines.JobSupport.makeCompletingOnce$kotlinx_coroutines_core(JobSupport.kt:829)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:97)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:28)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:99)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:102)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:585)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:802)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:706)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:693)
	Suppressed: java.lang.Error: Error: test
    at dictionaryapi (main.js:5)
    at <anonymous> (main.js:12)
    at search (main.js)
    at <eval> (main.js:2)

		at com.dokar.quickjs.QuickJs.getEvaluateResult(Native Method)
		at com.dokar.quickjs.QuickJs.evalAndAwait(QuickJs.jni.kt:220)
		at com.dokar.quickjs.QuickJs.evaluateInternal(QuickJs.jni.kt:210)
...
```

This js code works as expected when I define my own host.log function, but it would be nicer if I could catch the error in kotlin:
```
                    try {
                      doStuff();
                    }
                    catch (err) {
                      host.log("caught js error: ", err);
                    }
```

thanks for all your quick updates!

**Comment by dokar3** [comment]
You are welcome. 

And this looks weird, try-catch should work in Kotlin like [this test](https://github.com/dokar3/quickjs-kt/blob/e5212affd5bdef6886dd958470e14dfe624345c5/quickjs/src/commonTest/kotlin/com/dokar/quickjs/test/EvalErrorsTest.kt#L41), they are basically the same thing, but yours doesn't work.

I have no idea why Coroutines throws this error, can you provide more code or information code to reproduce it?

**Comment by dgmltn** [comment]
I see, yes the test looks the same to me. Let me see if I can reproduce in a demo app

**Comment by dgmltn** [comment]
Here's a JVM example that demonstrates the same issue (but a different stack trace). I would've thought that my try/catch would catch the thrown `Error`
```kotlin

fun main() {
    application {
        Window(onCloseRequest = ::exitApplication, title = "jsplayground") {
            App()
        }
    }
}

@Composable
fun App() {
    val scope = rememberCoroutineScope()
    var result by remember { mutableStateOf("") }

    val onRun = fun() {
        scope.launch {
            try {
                quickJs {
                    val js = """
                        throw new Error("test")
                    """.trimIndent()
                    result = evaluate<Any?>(js).toString()
                }
            }
            catch (e: Exception) {
                result = e.toString()
            }
        }
    }

    Column {
        Button(onRun) {
            Text("Click Me")
        }
        Text(result)
    }
}

```

**Comment by dgmltn** [comment]
For more infomation, if I change this code, the exception is thrown and caught properly:
```kotlin
            try {
                throw IOException("test fail from kotlin")
//                quickJs {
//                    val js = """
//                    throw new Error("test")
//                """.trimIndent()
//
//                    result = evaluate<Any?>(js).toString()
//                }
            }
            catch (e: Exception) {
                result = e.toString()
            }
```

**Comment by dokar3** [comment]
The sample code looks good to me, error propagation should work properly in this case. Anyway, will try this code later to see what I can find.

**Comment by dgmltn** [comment]
Thanks!

**Comment by dokar3** [comment]
The new version is out!

**Comment by dgmltn** [comment]
confirmed, working well for me!
